### ISSUE TITLE
Uncaught node.js Error 

### ISSUE THREAD

**Issue by ftoledo** [Mithgol/phido#6]
i clone the app doa npm install and try to run with node-webkit (0.11.2)

Uncaught node.js Error 

TypeError: Cannot read property 'exports' of undefined
    at file:///tmp/phido/index.html:18:14

**Comment by Mithgol** [comment]
Does the file `tmp/phido/node_modules/underscore.string/dist/underscore.string.min.js` exist after npm install?

**Comment by ftoledo** [comment]
Not exist. just tmp/phido/node_modules/underscore.string without *dist* directory 

toledones@gollum:/tmp/phido$ ls node_modules/underscore.string/
bower.json      foo.js       lib                    package.json
component.json  gulpfile.js  libpeerconnection.log  README.markdown

**Comment by Mithgol** [comment]
Thanks for reporting.
